### ISSUE TITLE
Make %discordsrv_user_top_role_name% placeholder respect DiscordChatChannelRolesSelection

### ISSUE THREAD

**Issue by pkrok01** [DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion#1]
Exactly what it says. Currently it looks for the highest discord role without checking the whitelist/blacklist, and it'd help since my discord server has a lot of misc roles.

**Comment by Vankka** [comment]
Fixed in https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion/commit/2ffd81b63e3eec48610b084e009bd092d45bf228 

Available for manual install through here: https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion/releases/tag/v1.3

i'll get it updated on ecloud aswell

**Comment by Vankka** [comment]
Now on ecloud
