### ISSUE TITLE
%discordsrv_user_top_role_color% gives me the hex #RGB instead of the translated DiscordChatChannelColorTranslations value

### ISSUE THREAD

**Issue by metalshark** [DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion#3]
When using %discordsrv_user_top_role_color% gives me the hex #RGB instead of the translated DiscordChatChannelColorTranslations value so I get a `#ffe32e` result instead of a `&e` whereas `%toprolecolor%` works fine and gives me `&e` when defining DiscordToMinecraftChatMessageFormat in messages.yml for DiscordSRV.

**Comment by Vankka** [comment]
`%discordsrv_user_top_role_color_code%`

Commit: https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion/commit/c9f173a5c0d4a0df90005400a1afba5ee6b84a60 

Manual Download: https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion/releases/tag/v1.4.1
Will be uploaded to ecloud *soon*

**Comment by LemmoTresto** [comment]
Uploaded to the ecloud.
